In [1]:
import numpy as np
import pandas as pd
import scipy as sp

In [3]:
from sklearn.preprocessing import Binarizer
dataframe=pd.read_csv('pima-indians-diabetes.csv')
array=dataframe.values

In [4]:
X=array[:,0:8]
Y=array[:,8]
binarizer=Binarizer(threshold=0.0).fit(X)
binaryX=binarizer.transform(X)

In [5]:
np.set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]]
