In [1]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [2]:
dataframe=pd.read_csv('pima-indians-diabetes.csv')
array=dataframe.values

In [3]:
X=array[:,0:8]
Y=array[:,8]

In [4]:
scaler=StandardScaler().fit(X)
rescalerX=scaler.transform(X)
np.set_printoptions(precision=3)
print(rescalerX[0:5,:])

[[-0.844 -1.122 -0.16   0.532 -0.694 -0.684 -0.364 -0.189]
 [ 1.234  1.944 -0.264 -1.287 -0.694 -1.102  0.605 -0.104]
 [-0.844 -0.997 -0.16   0.156  0.122 -0.493 -0.92  -1.04 ]
 [-1.141  0.505 -1.504  0.908  0.765  1.409  5.483 -0.019]
 [ 0.344 -0.152  0.253 -1.287 -0.694 -0.811 -0.817 -0.274]]
